//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrappr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wrappr.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Wrappr.
        /// </summary>
        public static string AboutAppButtonToolTip {
            get {
                return ResourceManager.GetString("AboutAppButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrappr is a desktop application that allows you to quickly and easily enable/disable Windows services and track their status..
        /// </summary>
        public static string AboutDescriptionText {
            get {
                return ResourceManager.GetString("AboutDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Wrappr.
        /// </summary>
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added to autostart successfully!.
        /// </summary>
        public static string AddedToAutoStartTitle {
            get {
                return ResourceManager.GetString("AddedToAutoStartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, move Wrappr.exe to safe place before using this feature to prevent accidental deletion..
        /// </summary>
        public static string AddTaskToSchedulerSubtitle {
            get {
                return ResourceManager.GetString("AddTaskToSchedulerSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Wrappr on login.
        /// </summary>
        public static string AddTaskToSchedulerTitle {
            get {
                return ResourceManager.GetString("AddTaskToSchedulerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrappr.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.1.
        /// </summary>
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string AutostartDisabled {
            get {
                return ResourceManager.GetString("AutostartDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check updates:.
        /// </summary>
        public static string CheckUpdates {
            get {
                return ResourceManager.GetString("CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Wrappr.
        /// </summary>
        public static string ContextMenuCloseApp {
            get {
                return ResourceManager.GetString("ContextMenuCloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Wrappr.
        /// </summary>
        public static string ContextMenuOpenApp {
            get {
                return ResourceManager.GetString("ContextMenuOpenApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new wrapper.
        /// </summary>
        public static string CreateNewWrapperTitle {
            get {
                return ResourceManager.GetString("CreateNewWrapperTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateWrapperButtonText {
            get {
                return ResourceManager.GetString("CreateWrapperButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create....
        /// </summary>
        public static string CreateWrapperPageRedirectButtonText {
            get {
                return ResourceManager.GetString("CreateWrapperPageRedirectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete wrapper.
        /// </summary>
        public static string DeleteWrapperButtonToolTip {
            get {
                return ResourceManager.GetString("DeleteWrapperButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administator.
        /// </summary>
        public static string ElevatedTitlebarText {
            get {
                return ResourceManager.GetString("ElevatedTitlebarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Wrapper.
        /// </summary>
        public static string EmptyWrapperDisplayName {
            get {
                return ResourceManager.GetString("EmptyWrapperDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No service set up.
        /// </summary>
        public static string EmptyWrapperServiceName {
            get {
                return ResourceManager.GetString("EmptyWrapperServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To create new wrapper click button below.
        /// </summary>
        public static string EmptyWrappersListPlaceholder {
            get {
                return ResourceManager.GetString("EmptyWrappersListPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorMessageTitle {
            get {
                return ResourceManager.GetString("ErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in tray at log in.
        /// </summary>
        public static string HideAtStart {
            get {
                return ResourceManager.GetString("HideAtStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources by Gregor Cresnar Premium from Flaticon.
        /// </summary>
        public static string LogoCreditsLink {
            get {
                return ResourceManager.GetString("LogoCreditsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App logo was made using.
        /// </summary>
        public static string LogoCreditsPrefix {
            get {
                return ResourceManager.GetString("LogoCreditsPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No service found.
        /// </summary>
        public static string NoServiceFoundPlaceholder {
            get {
                return ResourceManager.GetString("NoServiceFoundPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No service was selected.
        /// </summary>
        public static string NoServiceSelectedError {
            get {
                return ResourceManager.GetString("NoServiceSelectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-only.
        /// </summary>
        public static string NotElevatedTipTitlebarText {
            get {
                return ResourceManager.GetString("NotElevatedTipTitlebarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to show.
        /// </summary>
        public static string NoWrappersPopupPlaceholder {
            get {
                return ResourceManager.GetString("NoWrappersPopupPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This means that Wrappr cannot enable and disable services, change autostart settings, but can watch services statuses. To use full Wrappr functionality, please restart it with elevated privileges..
        /// </summary>
        public static string ReadOnlyModeDescription {
            get {
                return ResourceManager.GetString("ReadOnlyModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrappr is currently running without administrator privileges..
        /// </summary>
        public static string ReadOnlyModeTitle {
            get {
                return ResourceManager.GetString("ReadOnlyModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string ReloadAppButtonText {
            get {
                return ResourceManager.GetString("ReloadAppButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service with that name was not found.
        /// </summary>
        public static string ServiceNotFoundMessage {
            get {
                return ResourceManager.GetString("ServiceNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status of service &apos;{0}&apos; was externally changed to &apos;{1}&apos;.
        /// </summary>
        public static string ServiceStatusWasChangedBalloonText {
            get {
                return ResourceManager.GetString("ServiceStatusWasChangedBalloonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service status was changed.
        /// </summary>
        public static string ServiceStatusWasChangedBalloonTitle {
            get {
                return ResourceManager.GetString("ServiceStatusWasChangedBalloonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show at log in.
        /// </summary>
        public static string ShowAtStart {
            get {
                return ResourceManager.GetString("ShowAtStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code:.
        /// </summary>
        public static string SourcesPrefix {
            get {
                return ResourceManager.GetString("SourcesPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string WrapperGroupsPageTitle {
            get {
                return ResourceManager.GetString("WrapperGroupsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify.
        /// </summary>
        public static string WrapperNotificationsToggleText {
            get {
                return ResourceManager.GetString("WrapperNotificationsToggleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables/disables notifications for this wrapper. If enabled, Wrappr will send notification every time when status of wrapped service will be changed outside of Wrappr..
        /// </summary>
        public static string WrapperNotificationsToggleToolTip {
            get {
                return ResourceManager.GetString("WrapperNotificationsToggleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pooling delay.
        /// </summary>
        public static string WrapperPoolingDelayHint {
            get {
                return ResourceManager.GetString("WrapperPoolingDelayHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the time between service status checks (in ms). A lower value may put a strain on your system..
        /// </summary>
        public static string WrapperPoolingDelayToolTip {
            get {
                return ResourceManager.GetString("WrapperPoolingDelayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start typing service name....
        /// </summary>
        public static string WrapperSearchPlaceholder {
            get {
                return ResourceManager.GetString("WrapperSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrappers.
        /// </summary>
        public static string WrappersPageTitle {
            get {
                return ResourceManager.GetString("WrappersPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrappers.
        /// </summary>
        public static string WrappersTitle {
            get {
                return ResourceManager.GetString("WrappersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking.
        /// </summary>
        public static string WrapperTrackingToggleText {
            get {
                return ResourceManager.GetString("WrapperTrackingToggleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables/disables tracking for this wrapper. If enabled, Wrappr will keep track of the service status if it will be changed outside of Wrappr..
        /// </summary>
        public static string WrapperTrackingToggleToolTip {
            get {
                return ResourceManager.GetString("WrapperTrackingToggleToolTip", resourceCulture);
            }
        }
    }
}
